---
# This file exposes all relevant role variables as facts.
- name: Set slapd facts
  set_fact:
    slapd_run_dir: "{{ slapd_run_dir }}"
    slapd_ldapi_socket: "{{ slapd_ldapi_socket }}"
    slapd_mdb_dir: "{{ slapd_mdb_dir }}"
    slapd_olc_dir: "{{ slapd_olc_dir }}"
    slapd_schema_dir: "{{ slapd_schema_dir }}"
    slapd_user: "{{ slapd_user }}"
    slapd_group: "{{ slapd_group }}"
    slapd_olc_rootdn: "{{ slapd_olc_rootdn }}"
