---
- name: Install required packages (apt)
  apt:
    name: "{{ item }}"
  with_items:
    - slapd
    - ldap-utils
    - schema2ldif
  when: ansible_pkg_mgr == "apt"

- name: Install required packages (pacman)
  pacman:
    name: "{{ item }}"
  with_items:
    - openldap
  when: ansible_pkg_mgr == "pacman"

- name: Get schema2ldif
  get_url:
    url: "https://raw.githubusercontent.com/fusiondirectory/schema2ldif/master/bin/schema2ldif"
    dest: /usr/bin/schema2ldif
    mode: 0755
    owner: root
    group: root
  when: ansible_pkg_mgr == "pacman"

- name: Create slapd mdb location
  file:
    path: "{{ db_dir }}"
    state: directory
    owner: "{{ slapd_user }}"
    group: "{{ slapd_group }}"
    mode: 0770

- name: Create slapd OLC location
  file:
    path: "{{ olc_dir }}"
    state: directory
    owner: "{{ slapd_user }}"
    group: "{{ slapd_group }}"
    mode: 0770

- name: Create slapd unit
  template:
    src: slapd.service.j2
    dest: /etc/systemd/system/slapd.service
    mode: 0644
  register: unitfile

- name: Enable slapd unit
  service:
    name: slapd.service
    enabled: yes

- name: Create tmpfiles config
  template:
    src: tmpfiles.conf.j2
    dest: /etc/tmpfiles.d/slapd.conf
  register: tmpfiles

- name: Reload systemd
  command: /bin/systemctl daemon-reload
  when: unitfile.changed

- name: Create tmpfiles
  command: /bin/systemd-tmpfiles --create
  when: tmpfiles.changed
