---
# Sets up a basic and almost empty OLC
# slapd must not run.
- name: Check if OLC is initialized
  stat:
    path: "{{ olccreated_flag }}"
  register: olccreated

- name: Wipe default OLC
  file:
    path: "{{ olc_dir }}"
    state: absent
  when: not olccreated.stat.exists

- name: Create new slapd OLC location
  file:
    path: "{{ olc_dir }}"
    state: directory
    owner: "{{ slapd_user }}"
    group: "{{ slapd_group }}"
    mode: 0770

- name: Hash OLC password
  command: "/bin/bash -c '/usr/sbin/slappasswd -n -T /dev/stdin < <(echo -n $password)'"
  environment:
    password: "{{ olc_rootdn_password | mandatory }}"
  register: hashedPassword
  when: not olccreated.stat.exists
  changed_when: false

- name: Create basic OLC configuration
  template:
    src: slapd.conf.j2
    dest: "{{ olc_tmp }}"
    mode: 0444
  when: not olccreated.stat.exists

# Not using become the user may be overridden
- name: Apply basic OLC configuration
  command: "/usr/bin/sudo -u {{ slapd_user }} /usr/sbin/slaptest -f {{ olc_tmp }} -F {{ olc_dir }}"
  when: not olccreated.stat.exists

- name: Clean OLC configuration
  file:
    path: "{{ olc_tmp }}"
    state: absent

- name: Create OLC flag
  file:
    path: "{{ olccreated_flag }}"
    state: touch
  when: not olccreated.stat.exists

